<?php $scriptList = array("jquery-3.2.1.min.js", "carousel.js");
include("header.php");


?>

        <div id="main">
            <p>
                Welcome to Classic Cinema, your online store for classic film.
            </p>
			<div id="carousel">
                <!-- Content generated by JavaScript in carousel.js -->
            </div>
        </div>


        <?php include ("footer.php"); ?>
    </body>
</html>
